### PR TITLE
Bump terraform version and add setup-test-env.sh

### PR DESCRIPTION
**Pull request by futuretea**
- Bump terraform version to the latest 1.4.6
- Add a script setup-test-env.sh for test

try:
```bash
./setup-test-env.sh ~/.kube/config
```

### CODE REVIEW

**Comment by lanfon72** [comment]
@futuretea `v0.6.2` released but doc and provider example not bumped.

**Comment by futuretea** [comment]
@lanfon72 Fixed https://github.com/harvester/terraform-provider-harvester/pull/79/commits/93c10e5e7a44b062e0517d67bdf558092228db76

**Review by masteryyh — APPROVED** [review]
LGTM, thx.

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
