### PR TITLE
Clusternetwork import Enhancement

### PR DESCRIPTION
**Pull request by futuretea**
**Related issues**
https://github.com/harvester/harvester/issues/2052

### CODE REVIEW

**Comment by guangbochen** [comment]
does it mean we only support importing the `clusterNetwork` resources instead of allowing them to create it via the TF?

**Comment by guangbochen** [comment]
does it mean we only support importing the `clusterNetwork` resources instead of allowing them to create it via the TF?

**Comment by futuretea** [comment]
> does it mean we only support importing the `clusterNetwork` resources instead of allowing them to create it via the TF?

yes

**Review by guangbochen — APPROVED** [review]
LGTM

**Pull request merged**
