### PR TITLE
fix: release pipeline

### PR DESCRIPTION
**Pull request by FrankYang0529**
* change actions/checkout to v4
* change actions/setup-go to v5
* change go-version to v1.22
* change goreleaser/goreleaser-action to v6
* add "version: 2" to .goreleaser.yml
* remove darwin from .goreleaser.yml, because we import
longhorn/go-common-libs which uses unix.CLONE_NEWNET

### CODE REVIEW

**Review by Yu-Jack — APPROVED** [review]
LGTM, thanks!

**Review by bk201 — APPROVED** [review]

**Comment by rvdh** [comment]
I think this change cause the provider to be not available for me on macos:

│ Provider registry.terraform.io/harvester/harvester v0.6.5 does not have a package available for your current platform, darwin_amd64.

:(

**Comment by bk201** [comment]
@FrankYang0529 Can we see if we can enable darwin platform again?

**Comment by FrankYang0529** [comment]
Yeah, @Yu-Jack and I are checking on it.

**Comment by Yu-Jack** [comment]
@FrankYang0529 I think we need to modify longhorn/go-common-libs by creating different system go files. Here are two examples you could try that.

### Example

This example works with different builds.

- `GOOS=linux go build .`
- `GOOS=darwin go build .`

```go
// main.go
package main

import "fmt"

func main() {
	a := Namespace("test")
	fmt.Println(a.Flag())
}
```
```go
// namespace_linux.go
// go:build linux

package main

import (
	"fmt"

	"golang.org/x/sys/unix"
)

type Namespace string

const (
	NamespaceNet = Namespace("net")
)

func (ns Namespace) Flag() uintptr {
	fmt.Println("linux")
	switch ns {
	case NamespaceNet:
		return unix.CLONE_NEWNET
	default:
		return 0
	}
}
```
```go
// namespace_darwin.go
// go:build darwin

package main

import (
	"fmt"
)

type Namespace string

const (
	NamespaceNet = Namespace("net")
)

func (ns Namespace) Flag() uintptr {
	fmt.Println("darwin")
	return 0
}

```

### Example 2

This is a wrong example. It complains the error which is `undefined: unix.CLONE_NEWNET` same as we have.

```go
// namespace_darwin.go
// go:build darwin

package main

import (
	"fmt"

	"golang.org/x/sys/unix"
)

type Namespace string

const (
	NamespaceNet = Namespace("net")
)

func (ns Namespace) Flag() uintptr {
	fmt.Print(unix.CLONE_NEWNET)
	fmt.Println("darwin")
	return 0
}
```

So, we need to add `namespace_linux.go` and `namespace_darwin.go` for longhorn/go-common-libs.

**Comment by moio** [comment]
> @FrankYang0529 @Yu-Jack I think this change cause the provider to be not available for me on macos:
> 
> │ Provider registry.terraform.io/harvester/harvester v0.6.5 does not have a package available for your current platform, darwin_amd64.
> 
> :(

https://github.com/harvester/harvester/issues/6655 tracks that

**Pull request merged**
